POST http://localhost:3500/users
Content-Type: application/json

{
    "user_name": "kagiso",
    "user_email":"kagiso@gmail.com",
    "user_password":"kagiso2022",
    "user_contactNumber": "0755667788",
    "user_role": ""
}

###

PATCH  http://localhost:3500/users
Content-Type: application/json


{
    "user_email":"John@gmail.com",
    "user_password":"john2020"
}

###
GET  http://localhost:3500/users/

###
PUT http://localhost:3500/users/6228a52380c236ed0bb334f9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJrYWdpc28iLCJ1c2VyX2VtYWlsIjoia2FnaXNvQGdtYWlsLmNvbSIsInVzZXJfcGFzc3dvcmQiOiIkMmIkMTAkb2xENWtHci9GZmxXa3hybG5YVUQ2ZWtScVdjZUxYUEdDeFFlQVZsSmY2bXh0dVNSby9VUHEiLCJ1c2VyX2NvbnRhY3ROdW1iZXIiOiIwNzU1NjY3Nzg4IiwidXNlcl9yb2xlIjoidXNlcnIiLCJfaWQiOiI2MjI5OWZkYmU1YTAwZDQ3NTBhZTVkY2MiLCJfX3YiOjB9.8pu0jZ7kg9tg_BaZNDkP1toyHKDBWpJdKEJmm877Edw

{
    "user_name": "william",
    "user_email":"kagiso@gmail.com",
    "hashedPassword":"kagiso2020",
    "user_contactNumber": "0755667788",
    "user_role": "user"
}

###

DELETE http://localhost:3500/users/6228a36880c236ed0bb334f7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJrYWdpc28iLCJ1c2VyX2VtYWlsIjoia2FnaXNvQGdtYWlsLmNvbSIsInVzZXJfcGFzc3dvcmQiOiIkMmIkMTAkb2xENWtHci9GZmxXa3hybG5YVUQ2ZWtScVdjZUxYUEdDeFFlQVZsSmY2bXh0dVNSby9VUHEiLCJ1c2VyX2NvbnRhY3ROdW1iZXIiOiIwNzU1NjY3Nzg4IiwidXNlcl9yb2xlIjoidXNlcnIiLCJfaWQiOiI2MjI5OWZkYmU1YTAwZDQ3NTBhZTVkY2MiLCJfX3YiOjB9.8pu0jZ7kg9tg_BaZNDkP1toyHKDBWpJdKEJmm877Edw

###

POST http://localhost:3500/services
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJrYWdpc28iLCJ1c2VyX2VtYWlsIjoia2FnaXNvQGdtYWlsLmNvbSIsInVzZXJfcGFzc3dvcmQiOiIkMmIkMTAkb2xENWtHci9GZmxXa3hybG5YVUQ2ZWtScVdjZUxYUEdDeFFlQVZsSmY2bXh0dVNSby9VUHEiLCJ1c2VyX2NvbnRhY3ROdW1iZXIiOiIwNzU1NjY3Nzg4IiwidXNlcl9yb2xlIjoidXNlcnIiLCJfaWQiOiI2MjI5OWZkYmU1YTAwZDQ3NTBhZTVkY2MiLCJfX3YiOjB9.8pu0jZ7kg9tg_BaZNDkP1toyHKDBWpJdKEJmm877Edw


{
    "laundry_service": "Shoes",
    "service_price":"80",
    "service_image":"https://i.postimg.cc/m2GNHxvj/shoes.jpg"
}

###
GET  http://localhost:3500/services/

###
PUT http://localhost:3500/services/62306a5c575d90c8fe220ae6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJrYWdpc28iLCJ1c2VyX2VtYWlsIjoia2FnaXNvQGdtYWlsLmNvbSIsInVzZXJfcGFzc3dvcmQiOiIkMmIkMTAkb2xENWtHci9GZmxXa3hybG5YVUQ2ZWtScVdjZUxYUEdDeFFlQVZsSmY2bXh0dVNSby9VUHEiLCJ1c2VyX2NvbnRhY3ROdW1iZXIiOiIwNzU1NjY3Nzg4IiwidXNlcl9yb2xlIjoidXNlcnIiLCJfaWQiOiI2MjI5OWZkYmU1YTAwZDQ3NTBhZTVkY2MiLCJfX3YiOjB9.8pu0jZ7kg9tg_BaZNDkP1toyHKDBWpJdKEJmm877Edw

{
    "laundry_service": "Iron & Fold",
    "service_price":"50",
    "service_image":"https://i.postimg.cc/yYG5tmHS/iron-and-fold.jpg"
}

###

DELETE http://localhost:3500/services/622a078c1109e51093b2ad8e
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJrYWdpc28iLCJ1c2VyX2VtYWlsIjoia2FnaXNvQGdtYWlsLmNvbSIsInVzZXJfcGFzc3dvcmQiOiIkMmIkMTAkb2xENWtHci9GZmxXa3hybG5YVUQ2ZWtScVdjZUxYUEdDeFFlQVZsSmY2bXh0dVNSby9VUHEiLCJ1c2VyX2NvbnRhY3ROdW1iZXIiOiIwNzU1NjY3Nzg4IiwidXNlcl9yb2xlIjoidXNlcnIiLCJfaWQiOiI2MjI5OWZkYmU1YTAwZDQ3NTBhZTVkY2MiLCJfX3YiOjB9.8pu0jZ7kg9tg_BaZNDkP1toyHKDBWpJdKEJmm877Edw

###

GET http://localhost:3500/contact
Content-Type: application/json

{
    "name": "kagiso",
    "email":"kagiso@gmail.com",
    "subject":"akakaakaakakakkkakkakkakka",
    "message": "gdgdgdgdhduidfhsffdsjdghjdsgfljsgfsdghhykusdglfusgfsud"
}

###

POST http://localhost:3500/contact
Content-Type: application/json

{
    "name": "kao",
    "email":"ka@gmail.com",
    "subject":"akakaakaakakakkkakkakkakka",
    "message": "gdgdgdgdhduidfhsffdsjdghjdsgfljsgfsdghhykusdglfusgfsud"
}